# Generated by Django 5.2.13 on 2026-04-15 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0041_landingcarouselimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('chair', 'Chair'), ('table', 'Table'), ('decor', 'Decor'), ('equipment', 'Equipment'), ('other', 'Other')], default='other', max_length=30)),
                ('item_name', models.CharField(blank=True, default='', max_length=120)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('recovered_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('charge_to_client', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('billed', 'Billed to Client'), ('resolved', 'Resolved'), ('waived', 'Waived')], default='reported', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='damage_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_reports', to='user.booking')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damage_reports_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
