# Generated by Django 5.1.4 on 2026-04-21 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0043_booking_end_time_booking_extension_notified_1h_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='presidential_table_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='regular_table_price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.CreateModel(
            name='DamageCatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('chair', 'Chair'), ('table', 'Table'), ('glassware', 'Glassware'), ('utensil', 'Utensil'), ('decor', 'Decor'), ('equipment', 'Equipment'), ('other', 'Other')], default='other', max_length=30)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damage_catalog_items_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damage_catalog_items_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Damage Catalog Item',
                'verbose_name_plural': 'Damage Catalog Items',
                'ordering': ['item_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DamageReportLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(default='other', max_length=30)),
                ('item_name', models.CharField(max_length=150)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('catalog_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_items', to='user.damagecatalogitem')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='user.damagereport')),
            ],
            options={
                'verbose_name': 'Damage Report Line Item',
                'verbose_name_plural': 'Damage Report Line Items',
                'ordering': ['id'],
            },
        ),
    ]
