# Generated by Django 5.1.4 on 2026-04-21 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0044_eventtype_presidential_table_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='extension_notified_1h',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='extension_notified_30m',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='is_extended',
        ),
        migrations.RemoveField(
            model_name='eventtype',
            name='extension_fee',
        ),
        migrations.RemoveField(
            model_name='eventtype',
            name='extension_hours',
        ),
        migrations.DeleteModel(
            name='BookingExtension',
        ),
    ]
